name: CI

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  push_to_ghcr:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v2

      - name: Logging into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - id: lower-repo
        run: echo "repository=$(echo ${GITHUB_REPOSITORY,,})" >> $GITHUB_ENV

      - name: Pushing Image to Github Container Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ env.repository }}:latest